import localFont from "next/font/local";
import "./globals.css";
import { Inter, Poppins } from '@next/font/google';
import Navbar from "./Components/navbar";

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200','300','400','500','600', '700'], 
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <title>Quiz Spark</title>
    </head>
      <body
        className={poppins.variable}>
          <header>
            <Navbar />
          </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
